"""second migrate with create cars tableand add seats column

Revision ID: 0f47630424e1
Revises: 79b92c3df578
Create Date: 2021-06-23 16:04:41.558552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f47630424e1'
down_revision = '79b92c3df578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('seats', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'seats')
    # ### end Alembic commands ###
