"""Removed unique key in Customer tables

Revision ID: 5aa55de4deae
Revises: c6a433cab3b6
Create Date: 2021-06-30 23:54:31.752042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aa55de4deae'
down_revision = 'c6a433cab3b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customers_city', table_name='customers')
    op.create_index(op.f('ix_customers_city'), 'customers', ['city'], unique=False)
    op.drop_index('ix_customers_first_name', table_name='customers')
    op.create_index(op.f('ix_customers_first_name'), 'customers', ['first_name'], unique=False)
    op.drop_index('ix_customers_last_name', table_name='customers')
    op.create_index(op.f('ix_customers_last_name'), 'customers', ['last_name'], unique=False)
    op.drop_index('ix_customers_state', table_name='customers')
    op.create_index(op.f('ix_customers_state'), 'customers', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_state'), table_name='customers')
    op.create_index('ix_customers_state', 'customers', ['state'], unique=False)
    op.drop_index(op.f('ix_customers_last_name'), table_name='customers')
    op.create_index('ix_customers_last_name', 'customers', ['last_name'], unique=False)
    op.drop_index(op.f('ix_customers_first_name'), table_name='customers')
    op.create_index('ix_customers_first_name', 'customers', ['first_name'], unique=False)
    op.drop_index(op.f('ix_customers_city'), table_name='customers')
    op.create_index('ix_customers_city', 'customers', ['city'], unique=False)
    # ### end Alembic commands ###
