"""add relationship 

Revision ID: c6a433cab3b6
Revises: b28ac02e3db5
Create Date: 2021-06-29 16:06:01.699209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6a433cab3b6'
down_revision = 'b28ac02e3db5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('city', sa.String(length=255), nullable=False))
    op.add_column('customers', sa.Column('state', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_customers_city'), 'customers', ['city'], unique=True)
    op.create_index(op.f('ix_customers_state'), 'customers', ['state'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_state'), table_name='customers')
    op.drop_index(op.f('ix_customers_city'), table_name='customers')
    op.drop_column('customers', 'state')
    op.drop_column('customers', 'city')
    # ### end Alembic commands ###
